export { default as loginPage } from './loginPage'
export { default as registerPage } from './registerPage'
export { default as homePage } from './homePage'
export { default as achievementPage } from './achievementPage'
export { default as gamesPage } from './gamesPage'